name: Deploy

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        run: curl -XPOST http://192.168.0.13:9000/api/webhooks/e37c80b1-9315-49d2-b0ad-5b3d8dade98e
